accounts/urls.py
from django.urls import include, path
from django.contrib.auth.views import LoginView
from . import forms
from . import views

urlpatterns = [
    path('login/', LoginView.as_view(authentication_form=forms.UserLoginForm), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('profile/', views.get_profile, name='profile'),
    path('', include('django.contrib.auth.urls'))
]

project_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.utils.translation import gettext as _

admin.site.site_header = _("Project Management")
admin.site.site_title = _("Project Management")
urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path("admin/", admin.site.urls),
    path("", include("projects.urls")),
    path("accounts/", include("accounts.urls")),
]

projects/urls.py
from django.urls import path, include
from . import views
urlpatterns = [
    path("", views.ListProjectsView.as_view(), name="projects_list"),
    path("projects/creat", views.CreateProjectView.as_view(), name="projects_creat"),
    path("projects/update/<int:pk>", views.UpdateProjectView.as_view(), name="projects_update"),
    path("projects/delete/<int:pk>", views.DeleteProjectView.as_view(), name="projects_delete"),
    path("task/creat", views.CreatTaskView.as_view(), name="task_creat"),
    path("task/edite/<int:pk>", views.UpdateTaskView.as_view(), name="task_update"),
    path("task/delete/<int:pk>", views.DeleteTaskView.as_view(), name="Task_delete"),
]

projects/models.py
from django.db import models
from django.conf.global_settings import AUTH_USER_MODEL
from django.utils.translation import gettext as _


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Category")


class ProjectStatus(models.IntegerChoices):
    PENDING = 1, _("Pending")
    COMPLETED = 2, _("Completed")
    POSTPONED = 3, _("Postponed")
    CANCELED = 4, _("Canceled")


class Project(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    status = models.IntegerField(
        choices=ProjectStatus.choices,
        default=ProjectStatus.PENDING
    )
    create_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("Project")
        verbose_name_plural = _("Project")


class Task(models.Model):
    description = models.TextField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return self.description

    class Meta:
        verbose_name = _("Task")
        verbose_name_plural = _("Task")

projects/forms.py
from django import forms
from . import models
from django.utils.translation import gettext as _

attrs = {
    "class": "form-control"
}


class ProjectCreatForm(forms.ModelForm):
    class Meta:
        model = models.Project
        fields = ["title", "description", "category"]
        labels = {
            "title": _("Title"),
            "description": _("Description"),
            "category": _("Category"),

        }
        widgets = {
            'title': forms.TextInput(attrs=attrs),
            'description': forms.Textarea(attrs=attrs),
            'category': forms.Select(attrs=attrs),
        }


class ProjectUpdateForm(forms.ModelForm):
    class Meta:
        model = models.Project
        fields = ["title", "category", "status"]
        widgets = {
            "title": forms.TextInput(attrs=attrs),
            "category": forms.Select(attrs=attrs),
            "status": forms.Select(attrs=attrs),

        }

projects/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from . import models
from . import forms
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


# Create your views here.

class ListProjectsView(LoginRequiredMixin, ListView):
    model = models.Project
    template_name = "projects/list.html"
    paginate_by = 6

    def get_queryset(self):
        query_set = super().get_queryset()
        where = {"user_id": self.request.user}
        q = self.request.GET.get('q', None)
        if q:
            where['title__contains'] = q
        return query_set.filter(**where)


class CreateProjectView(LoginRequiredMixin, CreateView):
    model = models.Project
    form_class = forms.ProjectCreatForm
    template_name = "projects/creat.html"
    success_url = reverse_lazy("projects_list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class DeleteProjectView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = models.Project
    template_name = "projects/delete.html"
    success_url = reverse_lazy("projects_list")

    def test_func(self):
        return self.get_object().user_id == self.request.user.id


class UpdateProjectView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = models.Project
    form_class = forms.ProjectUpdateForm
    template_name = "projects/update.html"

    def test_func(self):
        return self.get_object().user_id == self.request.user.id

    # success_url = reverse_lazy("projects_list")
    def get_success_url(self):
        return reverse("projects_update", args=[self.object.id])


class CreatTaskView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = models.Task
    fields = ['description', 'project']
    http_method_names = ["post"]

    def test_func(self):
        project_id = self.request.POST.get('project', '')
        return models.Project.objects.get(pk=project_id).user_id == self.request.user.id

    def get_success_url(self):
        return reverse("projects_update", args=[self.object.project.id])


class UpdateTaskView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = models.Task
    fields = ["is_completed"]
    http_method_names = ['post']

    def test_func(self):
        return self.get_object().project.user_id == self.request.user.id

    def get_success_url(self):
        return reverse('projects_update', args=[self.object.project.id])


class DeleteTaskView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = models.Task

    def test_func(self):
        return self.get_object().project.user_id == self.request.user.id

    def get_success_url(self):
        return reverse("projects_update", args=[self.object.project.id])

projects/templates/projects/creat.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<div class="container">
	<div class="row justify-content-md-center">
		<div class="card col-md-6 px-0">
			<div class="card-header">
				<h3 class="mb-0 py-2">{% trans "New Project" %}</h3>
			</div>
			<div class="card-body">
				<form method="post">
					{% csrf_token %}
                    {% include "common/forms.html" with form=form  %}
                    <button class="btn btn-success"> {% trans "Create" %}</button>
				</form>
		</div>
	</div>
</div>
{% endblock %}

projects/templates/projects/delete.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
    <h2>{% trans "Alert" %}</h2>
    <form method="post">
        {% csrf_token %}
        <p class="text-muted my-4">{% trans 'Are you sure you want to delete ' %}"{{ project.title }}"?</p>

        <input class="btn btn-danger" type="submit" value="{% trans 'Delete' %}">

    </form>
{% endblock %}

projects/templates/projects/list.html
{% extends "base.html" %}
{% load i18n %}
{% load humanize %}

{% block content %}
    <div class=" d-flex">
        <h3 class="me-auto">
            {% trans "My Projects" %}
        </h3>
        <div>
            <a href="{% url 'projects_creat' %}" class="btn btn-outline-success" {% if object_list.count == 0 %} hidden="true" {% endif %}">
                <i class="bi bi-plus-lg "></i> {% trans "New Project" %}
            </a>

        </div>
    </div>
    <div class="row my-5">
	{% for project in object_list %}
	<div class="col-md-4">
		<div class="card">
			<div class="card-body">
				<p>
					<span class="badge rounded-pill bg-dark">
						{{project.get_status_display}}
					</span>
				</p>
				<h5 class="card-title fs-6">{{ project.title}}</h5>
				<p class="card-text test-muted small">{{ project.description }}</p>
                <div class="d-flex">
                    <span class="me-auto text-muted small">
                        <i class="bi bi-clock"></i>
                        <time datetime="{{ project.create_at }}">
                            {{ project.create_at|naturaltime }}
                        </time>
                    </span>
                    <a class="btn btn-sm btn-outline-dark mx-1" href="{% url 'projects_update' project.id %}">
                        {% trans "Edit" %}
                    </a>
                    <a class="btn btn-sm btn-outline-danger" href="{% url 'projects_delete' project.id %}">
                        {% trans "Delete" %}
                    </a>
                </div>
			</div>
		</div>
	</div>
    {% empty %}
        <div class="col-md-12">
            <div class="h-100 p-5 bg-white border rounded-3 text-center">
                <p >{% trans "There is no projects to show" %}</p>
                <p><i class="bi bi-emoji-frown fs-1"></i></p>

                <a href="{% url 'projects_creat' %}" class="btn btn-success">
                    <i class="bi bi-plus-lg "></i> {% trans "New Project" %}
                </a>
            </div>
        </div>
    {% endfor %}
    {% if page_obj.paginator.count > 0 %}
        <div class="d-flex justify-content-center bd-highlight mb-3 mt-3">
            <nav>
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">{% trans 'Previous' %}</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#">{% trans 'Previous' %}</a>
                        </li>
                    {% endif %}
                    {% for page_num in page_obj.paginator.page_range  %}
                        {% if page_obj.number == page_num%}
                            <li class="page-item disabled"><a class="page-link">{{ page_num }}</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
                        {% endif %}

                    {% endfor %}

                    {% if page_obj.has_next %}

                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">{% trans 'Next' %}</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#">{% trans 'Next' %}</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    
    {% endif %} 
</div>
{% endblock %}

projects/templates/projects/task.html
{% load i18n %}

<ul class="list-group">
    {% for task in project.task_set.all %}
        <li class="list-group-item d-flex">
            <form method="post" action="{% url 'task_update' task.id %} " class="my-auto me-2">
                {% csrf_token %}
                <input class="form-check-input"
                        type="checkbox"
                        name="is_completed"
                        {% if task.is_completed %} checked {% endif %}
                        onchange="this.form.submit()"
                />
            </form>
            <p class="my-auto me-auto">
                {{ task.description }}
            </p>
            <form method="post" action="{% url 'Task_delete' task.id %}">
                {% csrf_token %}
                <button type="submit" class="btn"><i class="bi bi-trash text-danger"></i></button>
            </form>
        </li>


    {% endfor %}
</ul>
<div class="card mt-2">
    <form method="post" action="{% url 'task_creat' %} " class="d-flex">
        {% csrf_token %}
            <div class="input-group">
                <input type="hidden" value="{{ project.id }}" name="project">
                <input type="text"  class="form-control" name="description" placeholder="{% trans "New Task" %}" required>
                <input value="{% trans "Add" %}" class="btn btn-outline-dark"  type="submit">
            </div>
    </form>
</div>

projects/templates/projects/update.html
{% extends "base.html" %}
{% load i18n %}
{% load humanize %}
{% block content %}
<nav aria-label="breadcrumb">
	<ol class="breadcrumb">
		<li class="breadcrumb-item active" aria-current="page">
			<h5>
				{{object.title}}
			</h5>
		</li>
	</ol>
</nav>

<div class="row">
	<div class="col-md-3">
		<form method="post">
			<div class="card">
				<div class="card-body">
					{% csrf_token %}
					{% for field in form %}
					<div class="mb-3">{{field}}</div>
					{% endfor %}
                    <div class="d-flex mt-2">
                    <span class="me-auto text-muted small">
                        <i class="bi bi-clock"></i>
                        <time datetime="{{ object.create_at }}">
                            {{ object.create_at|naturaltime }}
                        </time>
                    </span>
				</div>
				</div>
                <div class="card-footer">
                    <div class="d-grid gap-2">
                        <button class="btn btn-success">
                            <i class="bi bi-save"></i>
                            {% trans 'Save' %}
                        </button>

                        <a class="btn btn-danger" href="{% url 'projects_delete' object.id %}">
                            <i class="bi bi-trash"></i>
                            {% trans 'Delete' %}
                        </a>
                    </div>
                </div>
			</div>
		</form>
	</div>
    <div class="col-md-9">
        {% include "projects/task.html" with project=object %}
    </div>
</div>


{% endblock %}